import type { Key } from '../i18n';
import '../i18n/lazy/help';
import type { ShortcutPlace } from '../ui/shortcuts';

// Qué hace cada atajo del registro (src/ui/shortcuts.ts), en la ayuda. Va aparte del registro: el registro está
// en la primera carga y estos textos viajan con la ayuda. Una prueba revisa que cada atajo tenga el suyo.

export const SHORTCUT_TEXTS: Record<string, Key> = {
  search: 'shortcut.search',
  find: 'shortcut.find',
  print: 'shortcut.print',
  history: 'shortcut.history',
  assistant: 'shortcut.assistant',
  'titleEnter': 'shortcut.titleEnter',
  comment: 'shortcut.comment',
  question: 'shortcut.question',
  script: 'shortcut.script',
  'scriptEnter': 'shortcut.scriptEnter',
  pageBreak: 'shortcut.pageBreak',
  paragraph: 'shortcut.paragraph',
  collapse: 'shortcut.collapse',
  'collapseEveryone': 'shortcut.collapseEveryone',
  selectAll: 'shortcut.selectAll',
  heading: 'shortcut.heading',
  quote: 'shortcut.quote',
  numbered: 'shortcut.numbered',
  bullet: 'shortcut.bullet',
  checklist: 'shortcut.checklist',
  toggle: 'shortcut.toggle',
  undo: 'shortcut.undo',
  redo: 'shortcut.redo',
  indent: 'shortcut.indent',
  outdent: 'shortcut.outdent',
  moveUp: 'shortcut.moveUp',
  moveDown: 'shortcut.moveDown',
  lineBreak: 'shortcut.lineBreak',
  link: 'shortcut.link',
  bold: 'shortcut.bold',
  italic: 'shortcut.italic',
  underline: 'shortcut.underline',
  strike: 'shortcut.strike',
  code: 'shortcut.code',
  'mdSlash': 'shortcut.mdSlash',
  'mdHeading': 'shortcut.mdHeading',
  'mdBullet': 'shortcut.mdBullet',
  'mdNumbered': 'shortcut.mdNumbered',
  'mdChecklist': 'shortcut.mdChecklist',
  'mdQuote': 'shortcut.mdQuote',
  'mdDivider': 'shortcut.mdDivider',
  'mdCode': 'shortcut.mdCode',
  'photoOpen': 'shortcut.photoOpen',
  'photoRowNext': 'shortcut.photoRowNext',
  'photoRowPrev': 'shortcut.photoRowPrev',
  'photoRowLeave': 'shortcut.photoRowLeave',
  'photoRowEnter': 'shortcut.photoRowEnter',
  photoInlineSelect: 'shortcut.photoInlineSelect',
  photoInlineType: 'shortcut.photoInlineType',
  photoDelete: 'shortcut.photoDelete',
  pasteFiles: 'shortcut.pasteFiles',
  folderUp: 'shortcut.folderUp',
  'carretePrev': 'shortcut.carretePrev',
  'carreteNext': 'shortcut.carreteNext',
  'carreteEnds': 'shortcut.carreteEnds',
  'carreteClose': 'shortcut.carreteClose',
  'findNext': 'shortcut.findNext',
  'findPrev': 'shortcut.findPrev',
  'findClose': 'shortcut.findClose',
  'commentsSend': 'shortcut.commentsSend',
  'commentsCancel': 'shortcut.commentsCancel',
  'treeStep': 'shortcut.treeStep',
  'treeEnds': 'shortcut.treeEnds',
  'treeExpand': 'shortcut.treeExpand',
  'treeCollapse': 'shortcut.treeCollapse',
  'treeOpen': 'shortcut.treeOpen',
  'treeRename': 'shortcut.treeRename',
  'sidebarResize': 'shortcut.sidebarResize',
  'menusMove': 'shortcut.menusMove',
  'menusClose': 'shortcut.menusClose',
  'listPick': 'shortcut.listPick',
  'listClose': 'shortcut.listClose',
  versionName: 'shortcut.versionName',
  assistantApply: 'shortcut.assistantApply',
  tabsMove: 'shortcut.tabsMove',
  tourNext: 'shortcut.tourNext',
  tourBack: 'shortcut.tourBack',
  tourExit: 'shortcut.tourExit',
};

export const PLACE_TEXTS: Record<ShortcutPlace, Key> = {
  global: 'help.place.global',
  editor: 'help.place.editor',
  markdown: 'help.place.markdown',
  photos: 'help.place.photos',
  carrete: 'help.place.carrete',
  find: 'help.place.find',
  comments: 'help.place.comments',
  tree: 'help.place.tree',
  menus: 'help.place.menus',
  tour: 'help.place.tour',
};
