import type { BuiltinTexts } from './builtin';

// Las plantillas de fábrica en castellano (Docs/Doc_Plantillas.md, sección 2). Mismas filas y en el mismo orden que
// `builtin.en.ts` (una prueba lo compara): cambian solo los textos.

export const builtinEs: BuiltinTexts = {
  names: { prepro: 'Notas de preproducción', onset: 'Reporte de rodaje', shot: 'Desglose de plano' },
  descriptions: {
    prepro: 'Una página por escena: trabajo de VFX, lista de planos, elementos a filmar y preguntas al equipo.',
    onset: 'Una página por día de rodaje: cámara, planos y tomas, HDRI, medidas, marcadores y material.',
    shot: 'Una página por plano de VFX: cuadros, placas, trabajo, elementos, devoluciones y cotización.',
  },
  vfxWork: [
    'Extensión de decorado · matte painting',
    'Reemplazo de cielo',
    'Pantalla verde/azul',
    'Limpieza · borrado (rigs, cables, equipo)',
    'Elemento CG (criatura, vehículo, utilería)',
    'Simulación (fuego, humo, agua, destrucción)',
    'Multitudes',
    'Doble digital',
    'Inserts de pantallas (teléfonos, monitores)',
    'Fogonazos · impactos de bala',
    'Belleza · retoque',
    'Noche americana · reiluminación',
    'Retime · estabilización',
  ],
  questions: 'Preguntas',
  internal: 'Interno — borrar antes de compartir',
  prepro: {
    facts: [
      ['Escena'],
      ['Páginas de guion (octavos)'],
      ['Decorado · Locación'],
      ['INT/EXT · Día/Noche'],
      ['Días de rodaje previstos'],
      ['Elenco'],
      ['Dobles · Efectos especiales'],
      ['Planos de VFX (estim.)'],
      ['Estado', 'Borrador'],
    ],
    script: 'Guion',
    summary: 'Resumen',
    shotList: 'Lista de planos',
    shotListHeader: ['Plano', 'Ref', 'Descripción', 'Trabajo de VFX', 'Técnica', 'Complejidad'],
    vfxWork: 'Trabajo de VFX',
    approach: 'Cómo se hace',
    approachItems: ['Práctico o CG: ', 'Pantalla (color, tamaño): ', 'Cámara (fija, en mano, motion control): ', 'Lentes: '],
    elements: 'Elementos a filmar',
    elementItems: [
      'Placas limpias',
      'Pasadas de elementos (humo, polvo, chispas, sangre)',
      'Elementos para pantallas',
      'Referencia de actores · escaneo para doble digital',
      'Texturas · fotogrametría',
      'LiDAR',
      'HDRI por setup',
      'Cámaras testigo',
    ],
    setNeeds: 'Necesidades en set',
    setNeedItems: [
      'Pantallas: ',
      'Marcadores de tracking: ',
      'Luz interactiva: ',
      'Rigs y cables: ',
      'Coordinación con efectos especiales: ',
      'Playback en monitores: ',
      'Tiempo de VFX en el plan de rodaje: ',
    ],
    references: 'Referencias',
    questionItems: ['Director: ', 'DF: ', 'Arte: ', 'Efectos especiales · Dobles: ', 'Asistente de dirección: '],
    decisions: 'Decisiones',
    internalItems: ['Riesgos: ', 'Presupuesto · Cotización: '],
  },
  onset: {
    facts: [
      ['Fecha'],
      ['Día de rodaje'],
      ['Locación'],
      ['Decorados'],
      ['Unidad', 'Unidad principal'],
      ['Citación · Fin'],
      ['Clima'],
      ['Amanecer · Atardecer'],
      ['VFX en set'],
      ['Director · DF'],
    ],
    summary: 'Resumen',
    camera: 'Equipo de cámara',
    cameraHeader: ['Cám', 'Cuerpo', 'Modo de sensor · Resolución', 'EI · Balance de blancos', 'Juego de lentes', 'Notas'],
    cameraRows: ['A', 'B'],
    setups: 'Planos y tomas',
    setupsHeader: [
      'Claqueta (Esc · Plano · Setup)',
      'Cám · Clip · TC',
      'Lente · Filtros (ND, difusión, pola)',
      'T-stop · Foco',
      'Altura · Inclinación',
      'FPS · Obturador',
      'Tomas elegidas · Notas',
    ],
    vfxShots: 'Planos de VFX',
    shot: 'Plano ',
    shotChecks: [
      'Placa limpia',
      'HDRI',
      'Bola cromada y gris',
      'Carta de color',
      'Rejilla de lente · carta de distorsión (cada lente)',
      'Medidas',
      'Marcadores de tracking',
      'LiDAR · fotogrametría',
      'Cámara testigo',
      'Fotos de referencia',
      'Pasadas de elementos',
    ],
    light: 'Referencia de luz',
    lightHeader: ['Setup', 'HDRI (brackets · archivos)', 'Posición · Altura', 'Bola cromada y gris', 'Carta de color', 'Hora', 'Notas'],
    measurements: 'Medidas',
    measurementsHeader: ['Qué', 'Valor', 'Notas'],
    measurementRows: ['Cámara a sujeto', 'Altura de lente', 'Medidas del decorado', 'LiDAR · Fotogrametría'],
    markers: 'Marcadores de tracking',
    markerItems: ['Tipo y color: ', 'Dónde: ', 'Se sacaron después de: '],
    photos: 'Fotos de referencia',
    weather: 'Clima y luz',
    weatherItems: ['Mañana: ', 'Tarde: ', 'Noche: '],
    data: 'Material',
    dataHeader: ['Medio', 'Tarjeta · Rollo', 'Cantidad', 'Descargado en'],
    dataRows: ['Cámara A', 'Cámara B', 'HDRI', 'Rejillas de lente', 'LiDAR · Fotogrametría', 'Fotos de referencia', 'Cámara testigo'],
    issues: 'Pendientes',
    questionItems: ['Producción: ', 'Director: '],
  },
  shot: {
    facts: [
      ['Plano'],
      ['Escena'],
      ['Descripción'],
      ['Cuadros (entrada–salida · duración)'],
      ['Colas'],
      ['Placas (clip · TC)'],
      ['Lente'],
      ['Estado', 'Sin empezar'],
      ['Complejidad'],
      ['Entrega'],
    ],
    frame: 'Cuadro de referencia',
    vfxWork: 'Trabajo de VFX',
    technique: 'Técnica',
    elements: 'Elementos y assets',
    elementsHeader: ['Elemento', 'Tipo (placa, CG, elemento, matte)', 'Origen', 'Estado'],
    shootData: 'Datos de rodaje',
    shootDataRows: [['Día de rodaje (reporte)'], ['Cámara · Lente'], ['HDRI'], ['Placa limpia'], ['Medidas']],
    notes: 'Notas y devoluciones',
    notesHeader: ['Versión', 'Fecha', 'De', 'Notas'],
    questionItems: ['Director: '],
    internalRows: [['Artista · Proveedor'], ['Cotización (días)']],
  },
};
