import type { BuiltinTexts } from './builtin';

// Las plantillas de fábrica en inglés (Docs/Doc_Plantillas.md, sección 2). Cambiar un rótulo o una fila es una
// línea acá; las páginas ya creadas no cambian. El reporte del día (entrega 2) lee las filas de la ficha por su
// rótulo en los dos idiomas: si se renombra *Date*, *Location*, *Unit*… hay que sumar el nombre nuevo allá.

export const builtinEn: BuiltinTexts = {
  names: { prepro: 'Pre-production Notes', onset: 'On-Set Report', shot: 'Shot Breakdown' },
  descriptions: {
    prepro: 'One page per scene: VFX work, shot list, elements to shoot and questions for the crew.',
    onset: 'One page per shoot day: camera, setups and takes, HDRI, measurements, markers and data.',
    shot: 'One page per VFX shot: frames, plates, work, elements, feedback and bid.',
  },
  vfxWork: [
    'Set extension · matte painting',
    'Sky replacement',
    'Green/blue screen',
    'Cleanup · paint-out (rigs, wires, crew)',
    'CG element (creature, vehicle, prop)',
    'FX simulation (fire, smoke, water, destruction)',
    'Crowd',
    'Digi-double',
    'Screen inserts (phones, monitors)',
    'Muzzle flashes · bullet hits',
    'Beauty · retouch',
    'Day for night · relight',
    'Retime · stabilization',
  ],
  questions: 'Questions',
  internal: 'Internal — remove before sharing',
  prepro: {
    facts: [
      ['Scene'],
      ['Script pages (eighths)'],
      ['Set · Location'],
      ['INT/EXT · Day/Night'],
      ['Planned shoot days'],
      ['Cast'],
      ['Stunts · SFX'],
      ['VFX shots (est.)'],
      ['Status', 'Draft'],
    ],
    script: 'Script',
    summary: 'Summary',
    shotList: 'Shot list',
    shotListHeader: ['Shot', 'Ref', 'Description', 'VFX work', 'Technique', 'Complexity'],
    vfxWork: 'VFX work',
    approach: 'Approach',
    approachItems: ['Practical vs CG: ', 'Screen (color, size): ', 'Camera (locked-off, handheld, motion control): ', 'Lenses: '],
    elements: 'Elements to shoot',
    elementItems: [
      'Clean plates',
      'Element passes (smoke, dust, sparks, blood)',
      'Screen elements',
      'Actor reference · scan for digi-double',
      'Textures · photogrammetry',
      'LiDAR',
      'HDRI per setup',
      'Witness cameras',
    ],
    setNeeds: 'Set requirements',
    setNeedItems: [
      'Screens: ',
      'Tracking markers: ',
      'Interactive light: ',
      'Rigs and wires: ',
      'SFX coordination: ',
      'Playback on monitors: ',
      'VFX time in the schedule: ',
    ],
    references: 'References',
    questionItems: ['Director: ', 'DP: ', 'Production design: ', 'SFX · Stunts: ', '1st AD: '],
    decisions: 'Decisions',
    internalItems: ['Risks: ', 'Budget · Bid: '],
  },
  onset: {
    facts: [
      ['Date'],
      ['Shoot day'],
      ['Location'],
      ['Sets'],
      ['Unit', 'Main unit'],
      ['Call · Wrap'],
      ['Weather'],
      ['Sunrise · Sunset'],
      ['VFX on set'],
      ['Director · DP'],
    ],
    summary: 'Summary',
    camera: 'Camera package',
    cameraHeader: ['Cam', 'Body', 'Sensor mode · Resolution', 'EI · White balance', 'Lens set', 'Notes'],
    cameraRows: ['A', 'B'],
    setups: 'Setups & takes',
    setupsHeader: [
      'Slate (Sc · Shot · Setup)',
      'Cam · Clip · TC',
      'Lens · Filters (ND, diffusion, pola)',
      'T-stop · Focus',
      'Height · Tilt',
      'FPS · Shutter',
      'Circled takes · Notes',
    ],
    vfxShots: 'VFX shots',
    shot: 'Shot ',
    shotChecks: [
      'Clean plate',
      'HDRI',
      'Chrome & grey ball',
      'Color chart',
      'Lens grid · distortion chart (each lens)',
      'Measurements',
      'Tracking markers',
      'LiDAR · photogrammetry',
      'Witness camera',
      'Reference photos',
      'Element passes',
    ],
    light: 'Lighting reference',
    lightHeader: ['Setup', 'HDRI (brackets · files)', 'Position · Height', 'Chrome & grey ball', 'Color chart', 'Time', 'Notes'],
    measurements: 'Measurements',
    measurementsHeader: ['What', 'Value', 'Notes'],
    measurementRows: ['Camera to subject', 'Lens height', 'Set dimensions', 'LiDAR · Photogrammetry'],
    markers: 'Tracking markers',
    markerItems: ['Type and color: ', 'Where: ', 'Removed after: '],
    photos: 'Reference photos',
    weather: 'Weather & light',
    weatherItems: ['Morning: ', 'Afternoon: ', 'Night: '],
    data: 'Data',
    dataHeader: ['Media', 'Card · Roll', 'Count', 'Offloaded to'],
    dataRows: ['Camera A', 'Camera B', 'HDRI', 'Lens grids', 'LiDAR · Photogrammetry', 'Reference photos', 'Witness cam'],
    issues: 'Issues & follow-ups',
    questionItems: ['Production: ', 'Director: '],
  },
  shot: {
    facts: [
      ['Shot'],
      ['Scene'],
      ['Description'],
      ['Frames (in–out · length)'],
      ['Handles'],
      ['Plates (clip · TC)'],
      ['Lens'],
      ['Status', 'Not started'],
      ['Complexity'],
      ['Due'],
    ],
    frame: 'Reference frame',
    vfxWork: 'VFX work',
    technique: 'Technique',
    elements: 'Elements & assets',
    elementsHeader: ['Element', 'Type (plate, CG, element, matte)', 'Source', 'Status'],
    shootData: 'Shoot data',
    shootDataRows: [['Shoot day (report)'], ['Camera · Lens'], ['HDRI'], ['Clean plate'], ['Measurements']],
    notes: 'Notes & feedback',
    notesHeader: ['Version', 'Date', 'From', 'Notes'],
    questionItems: ['Director: '],
    internalRows: [['Artist · Vendor'], ['Bid (days)']],
  },
};
