// De dónde sale cada atajo del registro (shortcuts.ts): los archivos que lo manejan (los que se toman en `window`
// o en un componente) y las extensiones de BlockNote cuyas reglas de entrada lo hacen (lo que se escribe). Solo lo
// usan las pruebas (shortcuts.test.ts): no va en el bundle de la app. Un archivo nuevo que escucha teclas tiene que
// figurar acá, con su atajo en el registro y en la ayuda.

export const SHORTCUT_FILES: Record<string, string[]> = {
  search: ['Workspace.tsx', 'projectSearchUi.ts'],
  find: ['PageEditor.tsx', 'findUi.ts'],
  print: ['printPage.ts'],
  history: ['Workspace.tsx', 'historyUi.ts'],
  newDayReport: ['dayReportUi.tsx', 'dayReport.ts'],
  assistant: ['AssistantHost.tsx', 'assistantUi.ts'],
  titleEnter: ['PageView.tsx', 'PracticeView.tsx'],
  // Recién elegida una plantilla, Ctrl/⌘+Z en el título vacío deshace la página (templatesUi.ts).
  undo: ['PageView.tsx'],
  redo: ['PageView.tsx'],
  comment: ['EditorComments.tsx', 'commentsUi.ts'],
  selectAll: ['collapseEditor.ts'],
  photoOpen: ['PageEditor.tsx'],
  photoInlineSelect: ['inlinePhotoEditor.ts'],
  photoInlineType: ['inlinePhotoEditor.ts'],
  pasteFiles: ['PageEditor.tsx', 'inlinePhotoCreate.ts'],
  folderUp: ['FolderViewer.tsx'],
  carretePrev: ['Carrete.tsx'],
  carreteNext: ['Carrete.tsx'],
  carreteEnds: ['Carrete.tsx'],
  carreteClose: ['Carrete.tsx'],
  carreteAnnotate: ['Carrete.tsx'],
  annotateSelect: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateRectangle: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateEllipse: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateArrow: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateLine: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotatePencil: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateMarker: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateText: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateNumber: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateWidth: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateWidthNext: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateUndo: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateRedo: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateDelete: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateEscape: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateFit: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotatePan: ['annotatorKeys.ts', 'Annotator.tsx'],
  annotateSave: ['annotatorKeys.ts', 'Annotator.tsx'],
  findNext: ['FindBar.tsx', 'findUi.ts'],
  findPrev: ['FindBar.tsx', 'findUi.ts'],
  findClose: ['FindBar.tsx'],
  commentsSend: ['CommentsPanel.tsx', 'commentsUi.ts'],
  commentsCancel: ['CommentsPanel.tsx'],
  mentionPick: ['CommentsPanel.tsx'],
  mentionClose: ['CommentsPanel.tsx'],
  treeStep: ['Sidebar.tsx', 'treeNav.ts'],
  treeEnds: ['Sidebar.tsx', 'treeNav.ts'],
  treeExpand: ['Sidebar.tsx', 'treeNav.ts'],
  treeCollapse: ['Sidebar.tsx', 'treeNav.ts'],
  treeOpen: ['Sidebar.tsx', 'treeNav.ts'],
  treeRename: ['Sidebar.tsx'],
  sidebarResize: ['SidebarResizer.tsx'],
  menusMove: ['menus.tsx'],
  menusClose: [
    'menus.tsx',
    'MoveDialog.tsx',
    'ShareDialog.tsx',
    'MembersDialog.tsx',
    'DriveDialog.tsx',
    'PageFormatDialog.tsx',
    'ProjectStatesPart.tsx',
    'WorkspaceMenu.tsx',
    'Welcome.tsx',
    'AttachmentSheet.tsx',
    'Tooltip.tsx',
    'HelpDialog.tsx',
    'FolderDialog.tsx',
    'FolderDownload.tsx',
    'InstallDialog.tsx',
    'OfflinePart.tsx',
    'HistoryPanel.tsx',
    'ExportDialog.tsx',
    'AssistantPanel.tsx',
    'AssistantSettings.tsx',
    'SignOutDialog.tsx',
    'TemplateHost.tsx',
    'TemplateDialogs.tsx',
    'RootReportDialog.tsx',
  ],
  listPick: ['ProjectSwitcher.tsx', 'ProjectSearch.tsx', 'DrivePasteMenu.tsx'],
  // La confirmación de "Replace all" (ProjectReplace.tsx): Esc la cierra sin cerrar el panel.
  listClose: ['ProjectSwitcher.tsx', 'ProjectSearch.tsx', 'DrivePasteMenu.tsx', 'ProjectReplace.tsx'],
  versionName: ['HistoryPanel.tsx'],
  assistantApply: ['AssistantPanel.tsx'],
  tabsMove: ['InstallDialog.tsx'],
  tourNext: ['TourLayer.tsx'],
  tourBack: ['TourLayer.tsx'],
  tourExit: ['TourLayer.tsx'],
};

export const SHORTCUT_RULES: Record<string, string[]> = {
  mdHeading: ['heading-shortcuts'],
  mdBullet: ['bullet-list-item-shortcuts'],
  mdNumbered: ['numbered-list-item-shortcuts'],
  mdChecklist: ['check-list-item-shortcuts'],
  mdQuote: ['quote-block-shortcuts'],
  mdDivider: ['divider-block-shortcuts'],
  mdCode: ['code-block-keyboard-shortcuts'],
};
